### ISSUE TITLE
Error: failed to download "stable/coredns" 

### ISSUE THREAD

**Issue by ghost** [spender0/kubernetes-sandbox#2]
Hi @spender0 ,

Hope you are all well !

I tried your repository and docker-compose display the following error:
```sh
$ docker-compose up
Update Complete. ⎈ Happy Helming!⎈
Error: failed to download "stable/coredns" (hint: running `helm repo update` may help)
```

It seems that as of Nov 13, 2020, charts in this repo will no longer be updated.
https://github.com/helm/charts/tree/master/stable/coredns

Any idea how I can sort this problem ?

Cheers,
X

**Comment by ghost** [comment]
the same for kubernetes-dashboard, if I comment coredns lines.

```sh
Error: failed to download "stable/kubernetes-dashboard" (hint: running `helm repo update` may help)
```

**Comment by spender0** [comment]
@x0rzkov, thank you for finding the issue, I actualized helm repositories, should work now
